### ISSUE TITLE
Budget in negative values

### ISSUE THREAD

**Issue by Ghauoor** [coding-in-public/react-router-budget-app#1]
<img width="530" alt="Screenshot 2023-05-23 025302" src="https://github.com/coding-in-public/react-router-budget-app/assets/92637639/3ecfb143-530b-46a5-ad2e-80fe002201d2">

**Comment by coding-in-public** [comment]
Good spot, @Ghauoor. There are lots of little edge cases that I didn't handle in the series for length reasons. So it's not confusing for others (there being a difference between the video and this code), I probably won't fix this issue. Feel free to comment below with a fix for those who want it. Thanks!

**Comment by ASAPRKY** [comment]
Hey ..
If i buy the course on your website, do i have access to the entire code ?

**Comment by coding-in-public** [comment]
You can get the entire code by going to the latest branch ([here](https://github.com/coding-in-public/react-router-budget-app/tree/lesson-16)). No purchase necessary!
